repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: fmt
      - id: clippy
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
    - id: mdformat
      additional_dependencies:
        - mdformat-gfm
        - mdformat-frontmatter
        - mdformat-footnote
        - mdformat-gfm-alerts
      exclude: '^(fuzzers/aflpp/aflpp|examples/sudo/target)/.*'
