[book]
authors = [
    "Dimitri Kokkonis (dimitri.kokkonis@cea.fr)",
    "Michaël Marcozzi (michael.marcozzi@cea.fr)",
    "Emilien Decoux (emilien.decoux@protonmail.com)",
    "Stefano Zacchiroli (stefano.zacchiroli@cea.fr)",
]
language = "en"
multilingual = false
src = "src"
title = "ROSA: Finding Backdoors with Fuzzing"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/binsec/rosa"
