//! Metamorphic oracle definition & utilities.
//!
//! ROSA's backdoor detection is based on a metamorphic oracle: in order for something to be a
//! backdoor, it has to be different enough from similar but _normal_ runtime traces.
//!
//! This module implements various metamorphic oracle algorithms.

use std::{
    fmt,
    hash::{DefaultHasher, Hash, Hasher},
    str,
};

use serde::{Deserialize, Serialize};

use crate::{
    clustering::Cluster, criterion::Criterion, distance_metric::DistanceMetric, trace::Trace,
};

pub mod comp_min_max;

/// The interface to an oracle for ROSA.
///
/// The oracle is expected to compare a trace to a representative cluster and make a decision
/// (safe, suspicious) based on a [Criterion].
pub trait Oracle<DM>: Sync
where
    DM: DistanceMetric,
{
    /// The name of the oracle.
    const NAME: &'static str;

    /// Get the name of the oracle.
    fn name(&self) -> &'static str {
        Self::NAME
    }

    /// Decide if a given trace is safe or suspicious.
    ///
    /// The trace is compared to a corresponding (most similar) cluster, using a [Criterion] and a
    /// [DistanceMetric].
    fn decide(
        &self,
        trace: &Trace,
        cluster: &Cluster,
        criterion: Criterion,
        distance_metric: DM,
    ) -> Decision;
}

/// The reason for an oracle decision.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DecisionReason {
    /// The decision was made because the trace was a seed trace (i.e. it originated from the seed
    /// phase).
    #[serde(rename = "seed")]
    Seed,
    /// The decision was made because of the edges of the trace.
    #[serde(rename = "edges")]
    Edges,
    /// The decision was made because of the syscalls of the trace.
    #[serde(rename = "syscalls")]
    Syscalls,
    /// The decision was made because of both the edges and the syscalls of the trace.
    #[serde(rename = "edges-and-syscalls")]
    EdgesAndSyscalls,
    /// The decision was made because of diff filtering (through `rosa-filter-diff`).
    #[serde(rename = "diff-filtering")]
    DiffFiltering,
}

/// The edges and syscalls that lead to an oracle decision.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Discriminants {
    /// The edges that exist in the trace but not the cluster.
    pub trace_edges: Vec<usize>,
    /// The edges that exist in the cluster but not the trace.
    pub cluster_edges: Vec<usize>,
    /// The syscalls that exist in the trace but not the cluster.
    pub trace_syscalls: Vec<usize>,
    /// The syscalls that exist in the cluster but not the trace.
    pub cluster_syscalls: Vec<usize>,
}

impl Discriminants {
    /// The fingerprint of the discriminants.
    ///
    /// This fingerprint is produced by hashing the various discriminants and producing a string
    /// which corresponds to the relevant discriminants based on a criterion.
    /// We also incorporate the cluster UID in the UID of the discriminants, to ensure that the
    /// detection was made on the same basis. This lessens the deduplication, but makes collisions
    /// between detections less likely.
    pub fn fingerprint(&self, criterion: Criterion, cluster_id: &str) -> String {
        let mut hasher = DefaultHasher::new();
        let hash = match criterion {
            Criterion::EdgesOnly => {
                self.trace_edges.hash(&mut hasher);
                self.cluster_edges.hash(&mut hasher);
                hasher.finish()
            }
            Criterion::SyscallsOnly => {
                self.trace_syscalls.hash(&mut hasher);
                self.cluster_syscalls.hash(&mut hasher);
                hasher.finish()
            }
            Criterion::EdgesOrSyscalls | Criterion::EdgesAndSyscalls => {
                self.trace_edges.hash(&mut hasher);
                self.cluster_edges.hash(&mut hasher);
                self.trace_syscalls.hash(&mut hasher);
                self.cluster_syscalls.hash(&mut hasher);
                hasher.finish()
            }
        };

        format!("{:016x}_{}", hash, cluster_id)
    }
}

/// The decision made by an oracle.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Decision {
    /// The UID of the trace for which the decision was made.
    pub trace_id: String,
    /// The name of the trace for which the decision was made (usually generated by the fuzzer).
    pub trace_name: String,
    /// The UID of the cluster the trace was compared with.
    pub cluster_id: String,
    /// If [true], the trace is determined to be associated with a backdoor; otherwise, it is
    /// considered to be a normal trace.
    pub is_backdoor: bool,
    /// The reason for the decision.
    pub reason: DecisionReason,
    /// The discriminants (i.e., different edges and syscalls with regards to the cluster) that
    /// read to the decision.
    pub discriminants: Discriminants,
}

/// The timed decision made by an oracle.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct TimedDecision {
    /// The decision itself.
    pub decision: Decision,
    /// The amount of seconds the decision was made in (counting from the very start of the
    /// detection, i.e. the run phase).
    pub seconds: u64,
}

impl fmt::Display for DecisionReason {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Seed => "seed",
                Self::Edges => "edges",
                Self::Syscalls => "syscalls",
                Self::EdgesAndSyscalls => "edges-and-syscalls",
                Self::DiffFiltering => "diff-filtering",
            }
        )
    }
}
